---
- name: Install and Configure NGINX Server
  hosts: localhost
  become: yes 
  
  tasks:
    - name: Install NGINX Server
      apt:
        name: nginx
        state: present
        update_cache: yes 
      notify: Restart NGINX
  
    - name: Start and Enable NGINX Server
      service:
        name: nginx
        state: started
        enabled: yes 
  
    - name: Deploy static website  
      copy:
        src: index.html  
        dest: /var/www/html    
      notify: Restart NGINX

  handlers:
    - name: Restart NGINX
      service:
        name: nginx
        state: restarted
       
